name: Deploy content to site
on:
  workflow_dispatch:  
  push:
    branches:
      - main
    paths:
      - assets/**
      - content/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print hello world
      run: echo "Hello, World!"
